### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by RukaOff** [XtramCZ/auto-advertise-py#23]
Hello, I disabled 2FA and refreshed my page but it still displays that:
` > Token is invalid!
{"message": "401: Unauthorized", "code": 0}`

**Comment by RukaOff** [comment]
Ok, it work but now there is this:

>  > Changing status to online...
Traceback (most recent call last):
  File "c:\Users\rukao\Desktop\Auto Pub\main.py", line 184, in <module>
    asyncio.run(start())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\rukao\Desktop\Auto Pub\main.py", line 181, in start
    await sendMessages()
  File "c:\Users\rukao\Desktop\Auto Pub\main.py", line 132, in sendMessages
    message = open("message.txt", "r").read()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4: character maps to <undefined>

**Comment by XtramCZ** [comment]
There might be encoding issues in your message

Try changing the line 132 from
`message = open("message.txt", "r").read()`
to 
`message = open("message.txt", "r", encoding="utf-8").read()`

**Comment by RukaOff** [comment]
There is `Changing status to online`, `Going offline until 11:55`! It should work now ty

**Comment by RukaOff** [comment]
Just do you know what's the used time zone, because I live in France

**Comment by RukaOff** [comment]
What if we close VSCOde, will the code continue to run?

**Comment by XtramCZ** [comment]
No, you need a server for that
