### ISSUE TITLE
x

### ISSUE THREAD

**Issue by aken1111** [XtramCZ/auto-advertise-py#3]
Traceback (most recent call last):
  File "C:\Users\....\Desktop\dc\auto-advertise-py-main\main.py", line 157, in <module>
    asyncio.run(start())
  File "C:\Users\....\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\l....\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\....\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 709, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\....\Desktop\dc\auto-advertise-py-main\main.py", line 154, in start
    await sendMessages()
  File "C:\Users\....\Desktop\dc\auto-advertise-py-main\main.py", line 119, in sendMessages
    channel_name, guild_name = await getChannelInfo(channel_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\l....\Desktop\dc\auto-advertise-py-main\main.py", line 43, in getChannelInfo
    guild = requests.get(f'https://discord.com/api/v9/guilds/{channel["guild_id"]}', headers=headers).json()
                                                              ~~~~~~~^^^^^^^^^^^^
KeyError: 'guild_id'

C:\Users\....\Desktop\dc\auto-advertise-py-main>pause

**Comment by XtramCZ** [comment]
Hi, before I start working on a fix or something, can you check that the channel (id) exists and you are in the server?
